SEED_CLAIMS = [
    {
        "name": "Peyton Manning",
        "ssn": "245-67-8901",
        "date_of_birth": "1976-03-24",
        "amount": 2_500_000.00,
        "claim_type": "health",
        "description": "Post-career neck surgery follow-up and rehabilitation at Duke Medical Center",
    },
    {
        "name": "Brad Paisley",
        "ssn": "367-89-0123",
        "date_of_birth": "1972-10-28",
        "amount": 185_000.00,
        "claim_type": "home",
        "description": "Water intrusion damage to custom recording studio at Franklin, TN residence",
    },
    {
        "name": "Taylor Swift",
        "ssn": "478-90-1234",
        "date_of_birth": "1989-12-13",
        "amount": 4_200_000.00,
        "claim_type": "specialty",
        "description": "Eras Tour: total loss of lighting rig and Meyer Sound system — Kansas City stop",
    },
    {
        "name": "LeBron James",
        "ssn": "589-01-2345",
        "date_of_birth": "1984-12-30",
        "amount": 875_000.00,
        "claim_type": "health",
        "description": "Left foot tendon repair and eight-week physical therapy program",
    },
    {
        "name": "Dolly Parton",
        "ssn": "690-12-3456",
        "date_of_birth": "1946-01-19",
        "amount": 150_000.00,
        "claim_type": "specialty",
        "description": "Voice insurance: laryngitis-related tour cancellation, 3 dates in Nashville",
    },
    {
        "name": "Tom Hanks",
        "ssn": "701-23-4567",
        "date_of_birth": "1956-07-09",
        "amount": 45_000.00,
        "claim_type": "auto",
        "description": "T-bone collision on Mulholland Drive; 2022 Tesla Model S total loss",
    },
    {
        "name": "Oprah Winfrey",
        "ssn": "812-34-5678",
        "date_of_birth": "1954-01-29",
        "amount": 3_100_000.00,
        "claim_type": "home",
        "description": "Storm surge damage to Montecito estate — main house, guest cottage, and grounds",
    },
    {
        "name": "Garth Brooks",
        "ssn": "923-45-6789",
        "date_of_birth": "1962-02-07",
        "amount": 290_000.00,
        "claim_type": "specialty",
        "description": "Acoustic guitar collection (12 instruments) lost in transit between venues",
    },
    {
        "name": "Serena Williams",
        "ssn": "034-56-7890",
        "date_of_birth": "1981-09-26",
        "amount": 620_000.00,
        "claim_type": "health",
        "description": "Right knee ACL reconstruction and 16-week recovery protocol",
    },
    {
        "name": "Willie Nelson",
        "ssn": "145-67-8902",
        "date_of_birth": "1933-04-29",
        "amount": 55_000.00,
        "claim_type": "specialty",
        "description": "Trigger — 1969 Martin N-20 classical guitar: storm damage, humidity warping",
    },
]
